name: Улучшение
description: Предложить улучшение спецификации
title: "[IMPROVEMENT] "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Проблема
      description: Какую проблему решает предложение?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Предлагаемое решение
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Примеры и пограничные случаи
